quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=cliente
quarkus.datasource.password=cliente
quarkus.datasource.reactive.url=postgresql://localhost:5433/cliente

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

quarkus.http.port=8081
