spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/cliente
    username: cliente
    password: cliente
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
